name: 'AWS CLI'
description: 'Automate basic aws cli commands.'
inputs:
  TASK:
    description: 'Trigger the functionallity that is provided by this action.'
    required: true
  ACTION:
    description: 'What the cli will do'
    required: true
  IP:
    description: 'The IP that need to be add/remove from security group'
    required: false
  SG_ID:
    description: 'AWS Security group ID'
    required: false
outputs:
  CLI_RESPONSE:
    description: 'Return json response'
    value: ${{ steps.security_group_rules.outputs.RESPONSE }}
runs:
  using: "composite"
  steps:
    - name: Update Scurity Group rules
      id: security_group_rules
      if: (inputs.TASK == 'security_group_rules') && (inputs.IP != '[]')
      env:
        IP: ${{ inputs.IP }}
        SG_ID: ${{ inputs.SG_ID }}
        ACTION: ${{ inputs.ACTION }}
      shell: bash
      run: |
        if [ "$IP" == "runner_ip" ]; then
          THIS_IP=$(curl ifconfig.me)
        else
          THIS_IP="$IP"
        fi
        sudo apt install jq -y
        echo "-------------------------------"
        echo "Updating SG: $SG_ID"
        echo "IP: $THIS_IP"
        echo "ACTION: $ACTION"
        echo "-------------------------------"
        rule=$(aws ec2 describe-security-group-rules --filter Name="group-id",Values="$SG_ID" | jq ".[] | .[] | select(.CidrIpv4==\"$THIS_IP/32\")")
        EXECUTE=false
        if [ "$ACTION" == "authorize" ]; then
          if [ -z "$rule" ]; then
            EXECUTE=true
          fi
          AWS_ACTION="authorize-security-group-ingress"
          MSG="Rule exists ..."
        elif [ "$ACTION" == "revoke" ]; then
          if [ -n "$rule" ]; then
            EXECUTE=true
          fi
          AWS_ACTION="revoke-security-group-ingress"
          MSG="Rule does not exist ..."
        fi
        if [ $EXECUTE == true ]; then
          aws ec2 $AWS_ACTION --group-id $SG_ID --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=$THIS_IP/32,Description=\"Created by Github Action.\"}]"
        else
          echo "$MSG"
        fi
